### ISSUE TITLE
Questions on Depth images

### ISSUE THREAD

**Issue by changhaonan** [hsp-iit/fast-ycb#1]
Thanks for providing this dataset~
I am currently testing fast-YCB dataset for my own algorithm. I found a problem on the provided depth images. The depth images seems to be pre-filtered. If you turned into 3D, you can find something like this.

![000000](https://user-images.githubusercontent.com/16898838/204911105-a5014bd8-1c5f-4746-8bad-bcd2deff038b.png)

From my understanding, this is because there is a filter/averaging happening here between the foreground scene and background scene. So I wonder if you can provide the raw depth image data? (Without filtering).

**Comment by xEnVrE** [comment]
Hi @changhaonan,

thanks for showing interest in our dataset.

> From my understanding, this is because there is a filter/averaging happening here between the foreground scene and background scene.

Actually, the depth map we provide is the exact output we got from the renderer we used, i.e. the `xyz` renderer of [Mitsuba 2](https://www.mitsuba-renderer.org/). Hence, no averaging between background and foreground is taking place.

Probably the behavior you are seeing depends on the inner mechanisms of the renderer which tends to introduce such "noise".
Anyways, let me add that such kind of noise resembles what you get as output from several stereo vision systems - although not all. Some other stereo systems just have holes between foreground and background and do not filter between the two.

> So I wonder if you can provide the raw depth image data? (Without filtering).

Given the above, we could not provide any "raw" image as the raw ones are those already provided. Nonetheless, if you are working in the 3D domain directly, I would like to suggest using `DBSCAN` filtering to filter out the undesired noise.

Using `DBSCAN` filtering I was able to get this result:

![image](https://user-images.githubusercontent.com/6014499/205047998-1de614b0-35a3-42dd-9ee5-d5f00b7cb029.png)

the original being instead:

![image](https://user-images.githubusercontent.com/6014499/205048311-5fc76765-7690-4902-977e-883776b3478b.png)

Of course, some tuning of the `DBSCAN` parameters might be required depending on your goals.

Let me know if this helps. **I can provide the python code to reproduce the results above if you are interested in it**.

**Comment by changhaonan** [comment]
OK. Thanks. I current solved this problem by cutting out the surfaces that are too close to camera view angle. I know DBSCAN is a clustering method. So it can also help to remove outliers? Sounds interesting.

**Comment by xEnVrE** [comment]
> I current solved this problem by cutting out the surfaces that are too close to camera view angle.

Glad to know that you have solved it.

>  I know DBSCAN is a clustering method. So it can also help to remove outliers?

Most `DBSCAN` libraries assign `-1` as the label to a cluster including "noise", i.e. points not belonging to any valid cluster.

Feel free to close the issue if you think you are satisfied with your final solution. Thanks

**Comment by changhaonan** [comment]
Thanks.
