### ISSUE TITLE
Is it possible to add the result of ROFT into the benchmark?

### ISSUE THREAD

**Issue by changhaonan** [hsp-iit/fast-ycb#2]
Hi, 
I am a Ph.D working on 6d pose tracking. I'd like to include fast-ycb into my experiment. I notice that fast-ycb now provides gt, and dope results at each time-step. Is it possible to include the results from your method ROFT to this dataset?

**Comment by xEnVrE** [comment]
Hi @changhaonan,

thanks for showing interest in our dataset.

If you only need the results of `ROFT` on `fast-ycb` you can clone the `ROFT` repository and download the pre-evaluated results as follows:

```console
git clone https://github.com/hsp-iit/roft
cd roft
bash tools/download/download_results.sh
```

After the download completes, you will find a folder named `results` within `roft`. The results of `ROFT` on `fast-ycb` can be found in:
```
roft/results/ROFT_results/fastycb/full_mask_mrcnn_ycbv_bop_pbr_of_nvof_1_slow_pose_dope/<object_name>/pose_estimate.txt
```

Within the file, you can find for each row:                                                                                                                            
    - the estimated mixed linear velocity as `<v_x> <v_y> <v_z>` (in meter per second)                                                                            
    - the estimated mixed angular velocity as `<w_x> <w_y> <w_z>` (in radian per second)                                                                          
    - the estimated Cartesian position as `<x> <y> <z>` (in meter)                                                                                                
    - the estimated rotation as `<axis_x> <axis_y> <axis_z> <angle>` (i.e. axis/angle representation of the rotation) (the angle in radian)

The file `pose_estimate.txt` uses the the [NVDU](https://github.com/NVIDIA/Dataset_Utilities) version of the YCB Model Set meshes (those used in DOPE).

If, for any reason, you need the same results expressed in the reference frame of the [PoseCNN YCB Model set meshes](https://drive.google.com/file/d/1gmcDD-5bkJfcMKLZb3zGgH_HUFbulQWu/view?usp=sharing), please use instead the file `pose_estimate_ycb.txt`. The structure is the same as above except for the velocities that are not available and are replaced by `NaN`s.

Does this answer your question? Or, instead, you were asking if we could include those files within the dataset itself?

**Comment by changhaonan** [comment]
Thanks. I will have a try.

**Comment by xEnVrE** [comment]
Dear @changhaonan,

was the provided solution useful to solve your request?

Thanks

**Comment by changhaonan** [comment]
Yes. Sure. I will close this issue.
