### ISSUE TITLE
What is the format of the pose?

### ISSUE THREAD

**Issue by JiChun-Wang** [hsp-iit/fast-ycb#4]
Thanks for sharing the dataset. I want to kown if the format of pose is [trans_x, trans_y, trans_z, rot_w, rot_x, rot_y, rot_z] and if it represents the transformation from object frame to camera frame?

**Comment by xEnVrE** [comment]
Dear @JiChun-Wang, thanks for showing interest in our dataset.

> I want to kown if the format of pose is [trans_x, trans_y, trans_z, rot_w, rot_x, rot_y, rot_z]

The format of the poses is

$$ [ x, y, z, n_x, n_y, n_z, \theta] $$

where $p = (x, y, z)$ is the translation vector while $n = (n_x, n_y, n_z)$ is the axis of rotation and $\theta$ is the angle of rotation in radiant - we are not using a quaternion as it seemed from your previous comment.

The final transform is then

$$
T = 
\begin{bmatrix}
R & p\\
0^{T} & 1\\
\end{bmatrix}
$$

where $R = I + \sin(\theta) \hat{n} + (1 - \cos(\theta)) \hat{n}\hat{n}$ where $\hat{n}$ is the skew-symmetric matrix constructed out of the axis $n$.

> if it represents the transformation from object frame to camera frame

It is the opposite. It represents the transformation from the camera frame to the object frame.

Please let me know if this clarifies your doubt.

**Comment by xEnVrE** [comment]
I have updated the `README.md` to make sure the above information is available to everyone.
